In [2]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,4.0.6))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (91928307.py, line 1)

In [6]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [3]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [7]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [10]:
arr=np.ones((3,4))

In [11]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [13]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [14]:
np.empty((3,4))

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [15]:
arr1=np.eye(4)

In [16]:
arr1


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
import pandas as pd

In [18]:
pd.DataFrame(arr1)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [19]:
np.random.rand(2,3)

array([[0.34661813, 0.07874096, 0.27031255],
       [0.65663579, 0.45840949, 0.23229767]])

In [20]:
np.random.randn(2,3)

array([[-0.12539992, -0.01348735, -0.72994459],
       [ 0.19232715,  0.46543962,  2.64176275]])

In [24]:
arr2=np.random.randint(1,5,(3,4))

In [25]:
arr2

array([[1, 4, 2, 2],
       [2, 4, 1, 2],
       [2, 2, 4, 1]])

In [26]:
arr2.size

12

In [27]:
arr2.shape

(3, 4)

In [28]:
arr2.reshape(6,2)

array([[1, 4],
       [2, 2],
       [2, 4],
       [1, 2],
       [2, 2],
       [4, 1]])

In [29]:
arr2.reshape(4,3)

array([[1, 4, 2],
       [2, 2, 4],
       [1, 2, 2],
       [2, 4, 1]])

In [30]:
arr2.reshape(4,-1)

array([[1, 4, 2],
       [2, 2, 4],
       [1, 2, 2],
       [2, 4, 1]])

In [31]:
arr2.reshape(4,-1783462378)

array([[1, 4, 2],
       [2, 2, 4],
       [1, 2, 2],
       [2, 4, 1]])

In [36]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[1]]],


         [[[4]]],


         [[[2]]]],



        [[[[2]]],


         [[[2]]],


         [[[4]]]]],




       [[[[[1]]],


         [[[2]]],


         [[[2]]]],



        [[[[2]]],


         [[[4]]],


         [[[1]]]]]])

In [37]:
arr1=np.random.randint(1,10,(5,6))

In [38]:
arr1

array([[3, 7, 1, 1, 9, 1],
       [8, 1, 6, 6, 4, 2],
       [9, 4, 8, 7, 8, 9],
       [1, 1, 9, 1, 9, 4],
       [6, 9, 4, 1, 6, 6]])

In [40]:
arr1>5

array([[False,  True, False, False,  True, False],
       [ True, False,  True,  True, False, False],
       [ True, False,  True,  True,  True,  True],
       [False, False,  True, False,  True, False],
       [ True,  True, False, False,  True,  True]])

In [41]:
arr1[arr1>5]

array([7, 9, 8, 6, 6, 9, 8, 7, 8, 9, 9, 9, 6, 9, 6, 6])

In [42]:
arr1


array([[3, 7, 1, 1, 9, 1],
       [8, 1, 6, 6, 4, 2],
       [9, 4, 8, 7, 8, 9],
       [1, 1, 9, 1, 9, 4],
       [6, 9, 4, 1, 6, 6]])

In [43]:
arr1[0,[0,1]]

array([3, 7])

In [44]:
arr1[2:4,[2,3]]

array([[8, 7],
       [9, 1]])

In [45]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [46]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [47]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [48]:
arr1+arr2

array([[2, 3, 3],
       [2, 3, 2],
       [4, 2, 4]])

In [49]:
arr1*arr2


array([[1, 2, 2],
       [1, 2, 1],
       [4, 1, 4]])

In [50]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [51]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [52]:
arr1@arr2

array([[7, 7, 7],
       [4, 4, 4],
       [7, 6, 7]])

In [53]:
arr1/0

/tmp/ipykernel_126/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [54]:
##numpy broadCasting

In [55]:
arr=np.zeros((3,4
             ))

In [57]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [59]:
a=np.array([1,2,3,4])

In [60]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [61]:
b=np.array([[3,4,5]])

In [62]:
arr1=arr+b.T

In [63]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [64]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [65]:
np.log10(arr1
        )

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [66]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [67]:
np.min(arr1)

3.0

In [68]:
np.max(arr1)

5.0