In [1]:
import numpy as np

In [2]:
##Numpy array manupulation

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr

array([[4, 3, 1, 1],
       [4, 8, 4, 5],
       [3, 3, 2, 2],
       [6, 7, 8, 2]])

In [6]:
arr.reshape(8,2
           )

array([[4, 3],
       [1, 1],
       [4, 8],
       [4, 5],
       [3, 3],
       [2, 2],
       [6, 7],
       [8, 2]])

In [7]:
arr

array([[4, 3, 1, 1],
       [4, 8, 4, 5],
       [3, 3, 2, 2],
       [6, 7, 8, 2]])

In [8]:
arr.T



array([[4, 4, 3, 6],
       [3, 8, 3, 7],
       [1, 4, 2, 8],
       [1, 5, 2, 2]])

In [9]:
arr.flatten()

array([4, 3, 1, 1, 4, 8, 4, 5, 3, 3, 2, 2, 6, 7, 8, 2])

In [10]:
arr

array([[4, 3, 1, 1],
       [4, 8, 4, 5],
       [3, 3, 2, 2],
       [6, 7, 8, 2]])

In [12]:
np.expand_dims(arr,axis=1)

array([[[4, 3, 1, 1]],

       [[4, 8, 4, 5]],

       [[3, 3, 2, 2]],

       [[6, 7, 8, 2]]])

In [13]:
np.expand_dims(arr,axis=0)

array([[[4, 3, 1, 1],
        [4, 8, 4, 5],
        [3, 3, 2, 2],
        [6, 7, 8, 2]]])

In [14]:
data=np.array([[1],[2],[3]])

In [15]:
data

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [18]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [22]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
##Numpy Binary Operations

In [24]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [25]:
arr1

array([[3, 6, 5, 7],
       [5, 8, 5, 4],
       [2, 9, 2, 5]])

## 

In [26]:
arr2

array([[9, 8, 5, 2],
       [2, 6, 6, 1],
       [6, 2, 7, 6]])

In [27]:
~arr1

array([[ -4,  -7,  -6,  -8],
       [ -6,  -9,  -6,  -5],
       [ -3, -10,  -3,  -6]])

In [28]:
arr1>arr2

array([[False, False, False,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [ ]:
##Numpy String functions

In [30]:
arr=np.array(['anwar','hilal'])

In [31]:
arr

array(['anwar', 'hilal'], dtype='<U5')

In [32]:
arr.dtype

dtype('<U5')

In [34]:
np.char.upper(arr)

array(['ANWAR', 'HILAL'], dtype='<U5')

In [35]:
np.char.capitalize(arr)

array(['Anwar', 'Hilal'], dtype='<U5')

In [36]:
np.char.title(arr
             )

array(['Anwar', 'Hilal'], dtype='<U5')

In [37]:
arr

array(['anwar', 'hilal'], dtype='<U5')

In [38]:
##Numpy Mathematical function

In [39]:
arr1

array([[3, 6, 5, 7],
       [5, 8, 5, 4],
       [2, 9, 2, 5]])

In [41]:
np.sin(arr1)

array([[ 0.14112001, -0.2794155 , -0.95892427,  0.6569866 ],
       [-0.95892427,  0.98935825, -0.95892427, -0.7568025 ],
       [ 0.90929743,  0.41211849,  0.90929743, -0.95892427]])

In [42]:
np.tan(arr1)

array([[-0.14254654, -0.29100619, -3.38051501,  0.87144798],
       [-3.38051501, -6.79971146, -3.38051501,  1.15782128],
       [-2.18503986, -0.45231566, -2.18503986, -3.38051501]])

In [43]:
np.cos(arr1)

array([[-0.9899925 ,  0.96017029,  0.28366219,  0.75390225],
       [ 0.28366219, -0.14550003,  0.28366219, -0.65364362],
       [-0.41614684, -0.91113026, -0.41614684,  0.28366219]])

In [44]:
np.log10(arr1)

array([[0.47712125, 0.77815125, 0.69897   , 0.84509804],
       [0.69897   , 0.90308999, 0.69897   , 0.60205999],
       [0.30103   , 0.95424251, 0.30103   , 0.69897   ]])

In [45]:
np.exp(arr1)

array([[2.00855369e+01, 4.03428793e+02, 1.48413159e+02, 1.09663316e+03],
       [1.48413159e+02, 2.98095799e+03, 1.48413159e+02, 5.45981500e+01],
       [7.38905610e+00, 8.10308393e+03, 7.38905610e+00, 1.48413159e+02]])

In [46]:
np.power(arr1,3)

array([[ 27, 216, 125, 343],
       [125, 512, 125,  64],
       [  8, 729,   8, 125]])

In [47]:
np.mean(arr1)

5.083333333333333

In [48]:
np.max(arr1)

9

In [49]:
np.var(arr1)

4.409722222222222

In [50]:
np.std(arr1)

2.099933861392359

In [51]:
arr1


array([[3, 6, 5, 7],
       [5, 8, 5, 4],
       [2, 9, 2, 5]])

In [52]:
arr2

array([[9, 8, 5, 2],
       [2, 6, 6, 1],
       [6, 2, 7, 6]])

In [53]:
np.subtract(arr1,arr2)

array([[-6, -2,  0,  5],
       [ 3,  2, -1,  3],
       [-4,  7, -5, -1]])

In [54]:
np.multiply(arr1,arr2)

array([[27, 48, 25, 14],
       [10, 48, 30,  4],
       [12, 18, 14, 30]])

In [56]:
np.mod(arr1,arr2)

array([[3, 6, 0, 1],
       [1, 2, 5, 0],
       [2, 1, 2, 5]])

In [57]:
np.power(arr1,arr2)

array([[  19683, 1679616,    3125,      49],
       [     25,  262144,   15625,       4],
       [     64,      81,     128,   15625]])

In [58]:
np.sqrt(arr1)

array([[1.73205081, 2.44948974, 2.23606798, 2.64575131],
       [2.23606798, 2.82842712, 2.23606798, 2.        ],
       [1.41421356, 3.        , 1.41421356, 2.23606798]])

In [59]:
##Satitical Function

In [60]:
np.mean(arr1)

5.083333333333333

In [61]:
np.median(arr1)

5.0

In [62]:
np.std(arr1)

2.099933861392359