In [1]:
import numpy as np

In [3]:
l=[1,2,3,4,5]

In [4]:
arr=np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
arr1=np.array([[1,2,3],[2,3,4]])

In [11]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
arr1.ndim

2

In [14]:
arr.ndim

1

In [15]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [24]:
mat

matrix([[1, 2, 3, 4, 5]])

In [26]:
mat=np.matrix(l)

In [25]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [27]:
arr


array([1, 2, 3, 4, 5])

In [28]:
a=arr

In [29]:
a

array([1, 2, 3, 4, 5])

In [30]:
a[0]=12

In [31]:
a

array([12,  2,  3,  4,  5])

In [32]:
arr

array([12,  2,  3,  4,  5])

In [33]:
arr

array([12,  2,  3,  4,  5])

In [34]:
b=np.copy(a)

In [35]:
b

array([12,  2,  3,  4,  5])

In [36]:
b[0]=34

In [37]:
b


array([34,  2,  3,  4,  5])

In [38]:
a

array([12,  2,  3,  4,  5])

In [39]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [40]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
list(i*i for i in range(5) )

[0, 1, 4, 9, 16]

In [42]:
(i*i for i in range(5) )

<generator object <genexpr> at 0x7fb511a284a0>

In [44]:
itrable=(i*i for i in range(5) )

In [45]:
np.fromiter(itrable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
np.fromstring("11 2 233 44 55 ",sep=' ')

array([ 11.,   2., 233.,  44.,  55.])

In [47]:
arr

array([12,  2,  3,  4,  5])

In [48]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.ndim

1

In [52]:
arr1.ndim

2

In [53]:
arr.size

5